name: Build APK

on:
  push:
    branches: [main]
    paths: &shared_paths
      - "packages/**"
      - ".github/**"
      - "openwrt-packages-extended.pub"
  pull_request:
    branches: [main]
    paths: *shared_paths

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64-25.12.4, x86_64-25.12.5]
    steps:
      - uses: actions/checkout@v7

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          INDEX: 1
          PRIVATE_KEY: ${{ secrets.APK_PRIVATE_KEY }}

      - name: Prepare Deployment Directory
        run: |
          mkdir -p public/packages/${{ matrix.arch }}
          cp -r bin/packages/*/action/* public/packages/${{ matrix.arch }}/
          cp openwrt-packages-extended.pub public/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.arch }}-repository
          path: public/

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: public
          pattern: "*-repository"
          merge-multiple: true

      - name: Generate Directory Index
        run: python3 .github/scripts/generate-index.py

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
